image:
  repository: hammadddd/automated_devops_pipeline_project
  tag: 85c8108
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  ebabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false