---

name: Automated DevOps Pipeline Project

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Build Docker Image
        run: |
          docker build -t hammadddd/automated_devops_pipeline_project:${{ env.SHORT_SHA }} .
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push to Dockerhub 
        run: |
          docker push hammadddd/automated_devops_pipeline_project:${{ env.SHORT_SHA }}
          
#changed token